### ISSUE TITLE
I think the linter might be using another alphabet than the one i know.

### ISSUE THREAD

**Issue by miklschmidt** [secoya/tslint-secoya#3]
![screen shot 2017-04-21 at 2 01 21 am](https://cloud.githubusercontent.com/assets/751171/25257187/836c10ba-2636-11e7-870b-4164269bc8a4.png)
![screen shot 2017-04-21 at 2 01 30 am](https://cloud.githubusercontent.com/assets/751171/25257192/863a42b2-2636-11e7-9def-f67889e2ea7f.png)

**Comment by bondo** [comment]
I think it's sorted by path, not what's imported

**Comment by miklschmidt** [comment]
Aaah, that makes sense, isn't that weird though?

**Comment by thetrompf** [comment]
It is sorted by this.

```
core!project%relay/components/task-assignment-action
core!project%relay/components/task-assignment-action
core/components/react/icons/activity
core/components/react/icons/arrow-down
core/components/react/portal_popover
types!project%relay/components/node-actions
```

The idea is files imported from the same place is grouped together, so all project stuff is groped and all core/components subpaths are group.

It breaks a bit when we custom loaders like: `com!` and `types!` which potentially could load stuff from the same place.

**Comment by miklschmidt** [comment]
I mean, objects aren't sorted by the values? Isn't it the same thing here?

**Comment by kastermester** [comment]
Well, it doesn't really make sense to sort the entire line by its text. When you add a new import to from a file you end up changing the order of that import line, that's not really cool.

The import path is not a value in the sense of ordering objects by value. This is again about making the code predictable - if you know what sort of import you are looking for you can scan for it easily. The components you import *also* needs to be ordered, by they do not, and IMO, should not affect where in the file the statement that imports it is located.

**Comment by miklschmidt** [comment]
> Well, it doesn't really make sense to sort the entire line by its text. When you add a new import to from a file you end up changing the order of that import line, that's not really cool.

Ah yes, i see!

> The import path is not a value in the sense of ordering objects by value. This is again about making the code predictable - if you know what sort of import you are looking for you can scan for it easily. The components you import also needs to be ordered, by they do not, and IMO, should not affect where in the file the statement that imports it is located.

That makes sense. I'll go ahead and close this.
